<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Laraue.Core.DataAccess.EFCore" Version="10.8.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Laraue.Apps.Billing.Internal.Contracts\Laraue.Apps.Billing.Internal.Contracts.csproj" />
    </ItemGroup>

</Project>
